apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- secret.yaml

images:
- name: jmuachifi/barbershop-django-app # Replace with your image name
  newTag: latest # Will dynamically update this during the pipeline
