apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc
spec:
  accessModes:
  - ReadWriteOnce # Single-node access
  resources:
    requests:
      storage: 1Gi # 1GB of storage for the SQLite file
