name: Deploy Django App with ArgoCD

on:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  # 1. Code Quality Stage
  code_quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black

    - name: Run Flake8 for Code Style Check
      run: |
        flake8 --max-line-length=88

    - name: Run Black for Code Formatting
      run: |
        black --check .

  # 2. Security Check Stage
  security_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Bandit for Python Security Analysis
      run: |
        pip install bandit

    - name: Run Bandit Security Check
      run: |
        bandit -r .

    - name: Install Trivy for Container Security Scanning
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: jmuachifi/barbershop-django-app:latest

  # 3. Build and Push Docker Image
  build:
    runs-on: ubuntu-latest
    needs: [code_quality, security_check]  # This ensures code quality and security checks pass before building

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build --tag jmuachifi/barbershop-django-app:$GITHUB_SHA -t jmuachifi/barbershop-django-app:latest  .
        docker push jmuachifi/barbershop-django-app:latest
        docker push jmuachifi/barbershop-django-app:$GITHUB_SHA

  # 4. Update kustomization.yaml and Commit Changes
  update_kustomization:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update kustomization.yaml with new image tag
      run: |
        git remote set-url origin https://jmuachifi:${{ secrets.GH_PAT }}@github.com/jmuachifi/barbershop-django-argocd.git
        sed -i "s@newTag:.*@newTag: $GITHUB_SHA@g" k8s/kustomization.yaml
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git commit -am "Update image tag to $GITHUB_SHA [skip ci]"
        git push origin main

  # 5. Deploy with ArgoCD
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: update_kustomization

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Log in to ArgoCD
  #     run: |
  #       argocd login ${{ secrets.ARGOCD_SERVER }} --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --insecure

  #   - name: Sync ArgoCD Application
  #     run: |
  #       argocd app sync django-app
